title: MinecraftHopper
email: admin@minecrafthopper.net
description: >-
  Get community help for Minecraft
baseurl: ""
url: "https://minecrafthopper.net"
twitter_username: ""
github_username:  ""
paste_site: "[PasteBook](https://pastebook.dev/new)"
paste_site_name: "PasteBook"

markdown: kramdown
theme: jekyll-theme-cayman

collections:
    help:
        output: true

plugins:
  - jekyll-redirect-from